services:
  app:
    build:
      target: development
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"

  cli:
    build:
      target: cli
    volumes:
      - ./:/home/node/app
